# Generated by Django 6.0 on 2026-04-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
