# Generated by Django 6.0 on 2026-02-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='bgImage',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
