# Generated by Django 6.0 on 2026-04-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelryitem',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
