# Generated by Django 6.0 on 2026-04-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_jewelryitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelryitem',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
