# Generated by Django 6.0 on 2026-04-03 17:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_jewelryitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelryitem',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='jewelryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
